name: Daily Snapshot

on:
  schedule:
    # Ora legale (Apr–Ott): 17:35 Rome = 15:35 UTC
    - cron: "35 15 * 4-10 1-5"
    # Ora solare (Nov–Mar): 17:35 Rome = 16:35 UTC
    - cron: "35 16 * 1-3,11,12 1-5"
  workflow_dispatch: {}

jobs:
  run-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          FUND_TAB: Fondamentali
          HIST_TAB: Storico
        run: python snapshot.py
